apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-janitor
    version: v0.1
  name: kube-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-janitor
  template:
    metadata:
      labels:
        application: kube-janitor
        version: v0.1
    spec:
      serviceAccountName: kube-janitor
      containers:
      - name: janitor
        # see https://github.com/hjacobs/kube-janitor/releases
        image: hjacobs/kube-janitor:0.1
        args:
          # dry run by default, remove to perform clean up
          - --dry-run
          # run every minute
          - --interval=60
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
